<?php

namespace App\Business;

use Illuminate\Database\Eloquent\Model;

class Reporte extends Model {
    protected $table = 'reporte';
    protected $primaryKey = 'id';

    public static function getIncome() {
        return [
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            /*
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'mar 25 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 5000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'lun 24 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 6000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],
            (object)[
                'fecha' => 'dom 23 abril',
                'cuenta1_nombre' => 'Terminal Atocongo',
                'cuenta1_ingreso' => 8000.00,
                'cuenta2_nombre' => 'La Victoria',
                'cuenta2_ingreso' => 2000.00,
                'cuenta_total' => 2,
            ],*/
        ];
    }
}
?>